CREATE TABLE AUTHORS (
    Author_id INTEGER PRIMARY KEY,
    Name TEXT NOT NULL
);

CREATE TABLE BOOK (
    ISBN10 TEXT PRIMARY KEY,
    Title TEXT NOT NULL
);

CREATE TABLE BOOK_AUTHORS (
    ISBN10 TEXT,
    Author_id INTEGER,
    FOREIGN KEY (ISBN10) REFERENCES BOOK(ISBN10),
    FOREIGN KEY (Author_id) REFERENCES AUTHORS(Author_id),
    PRIMARY KEY (ISBN10, Author_id)
);

CREATE TABLE BORROWER (
    Card_id TEXT PRIMARY KEY,
    Ssn TEXT UNIQUE NOT NULL,
    Bname TEXT NOT NULL,
    Address TEXT NOT NULL,
    Phone TEXT NOT NULL
);

CREATE TABLE BOOK_LOANS (
    Loan_id INTEGER PRIMARY KEY AUTOINCREMENT,
    ISBN10 TEXT NOT NULL,
    Card_id TEXT NOT NULL,
    Date_out DATE NOT NULL,
    Due_date DATE NOT NULL,
    Date_in DATE,
    FOREIGN KEY (ISBN10) REFERENCES BOOK(ISBN10),
    FOREIGN KEY (Card_id) REFERENCES BORROWER(Card_id)
);

CREATE TABLE FINES (
    Loan_id INTEGER PRIMARY KEY,
    Fine_amt DECIMAL(10, 2) NOT NULL CHECK (Fine_amt >= 0),
    Paid BOOLEAN DEFAULT 0,
    FOREIGN KEY (Loan_id) REFERENCES BOOK_LOANS(Loan_id)
);